### ISSUE TITLE
Release 1.7.0

### ISSUE THREAD

**Issue by mkouba** [quarkusio/gizmo#159]
This release will include the new `ClassTransformer` API introduced in https://github.com/quarkusio/gizmo/commit/3080339661adec292c46df6770ec70438c78a2b8.

**Comment by gsmet** [comment]
@mkouba Gizmo `1.7.0` (I dropped the `.Final` suffix here too) is on its way to Maven Central.

**Comment by mkouba** [comment]
> @mkouba Gizmo `1.7.0` (I dropped the `.Final` suffix here too) is on its way to Maven Central.

Thanks!
