### ISSUE TITLE
No source JAR included for `gizmo-xxx-tests.jar`

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/gizmo#202]
We publish `gizmo-xxx-tests.jar` for consumption in other projects, like Quarkus. However, this JAR does not have a source artifact, making debugging and code analysis tricky and annoying.

**Comment by gsmet** [comment]
I think the build intends to do it, not sure how it should be fixed:

**Comment by gsmet** [comment]
I see a `test-sources` jar here: https://repo1.maven.org/maven2/io/quarkus/gizmo/gizmo/1.8.0/

**Comment by dmlloyd** [comment]
Ah, you're right. I guess Intellij doesn't know how to find it from central - and also, it is not built by default when doing an `mvn install` from the command line (at least it didn't appear in `target/` for me).

I did `mvn dependency:get -Dartifact=io.quarkus.gizmo:gizmo:1.8.0:jar:test-sources` and it downloaded it, and IDEA found it right away.
