### ISSUE TITLE
Add more if statements

### ISSUE THREAD

**Issue by mkouba** [quarkusio/gizmo#39]
Currently, we only have `ifNonZero` and `ifNull`. It would be useful to add more variants, `ifgt` or `iflt` at least.

**Comment by stuartwdouglas** [comment]
Are you planning on looking into this?

**Comment by mkouba** [comment]
Well, I'd like to but I wonder whether to simply add `ifGreaterThanZero()` etc., or whether to add some more generic solution. WDYT?

**Comment by mkouba** [comment]
I'll try to send a PR with a more general solution later today...
