### ISSUE TITLE
Upgrade to ASM 9

### ISSUE THREAD

**Issue by Sanne** [quarkusio/gizmo#61]
Hi,

Byte Buddy is using ASM9 now; I'd like to update the Byte Buddy used in Hibernate ORM.

Technically the version used by Hibernate via Byte Buddy doesn't have to be the same as Gizmo as ASM is being shaded, but I'd not want too much trouble :)

@stuartwdouglas , WDYT ?

Thanks

**Comment by stuartwdouglas** [comment]
I have no objections.

**Comment by FroMage** [comment]
Me neither, go for it.

**Comment by Sanne** [comment]
thanks, sent a PR
