### ISSUE TITLE
BytecodeCreator.invokeSpecialMethod() cannot be used for interface default methods

### ISSUE THREAD

**Issue by mkouba** [quarkusio/gizmo#9]
It should be possible to use the `invokeSpecial` instruction to invoke an interface default method. However, `BytecodeCreator.invokeSpecialMethod() ` always adds an `InvokeOperation` with `interfaceMethod=false` (constant pool contains `Methodref` instead of  `InterfaceMethodref`).

We could either add a special method, something like `BytecodeCreator.invokeSpecialInterfaceMethod()` or add a variant with `interfaceMethod` boolean parameter.

**Comment by mkouba** [comment]
@stuartwdouglas WDYT?

**Comment by stuartwdouglas** [comment]
I think an extra parameter makes sense.

**Comment by mkouba** [comment]
I'll send a PR shortly.

**Comment by mkouba** [comment]
Hm, that's interesting. It's not a problem for JVM and the generated bytecode works fine even if it looks broken. In other words JVM does not care whether the constant pool contains `Methodref` or `InterfaceMethodref`.

I have a fix here: https://github.com/mkouba/gizmo/tree/invoke-special

But I'm not really sure if it makes sense to send a PR.

**Comment by mkouba** [comment]
> I _think_ this was actually fixed by #93.

I think so.
